import {
  ShieldCheck,
  RotateCcw,
  MessageSquareText,
  BadgeCheck,
  Truck,
  Zap,
  Banknote,
  Smartphone,
  ShieldPlus,
  ShieldHalf,
  Target,
  Columns3,
  Heart,
  ShoppingCart,
  Accessibility,
  Headset,
  BadgePercent,
  TrendingDown,
  MapPin,
  LayoutGrid,
  Laptop,
  Headphones,
  Camera,
  Watch,
  Tablet,
  Speaker,
  Tv,
  Search,
  User,
  Menu,
  X,
  Star,
  Minus,
  Plus,
  ChevronLeft,
  ChevronRight,
  Trash2,
  Edit,
  CheckCircle,
  AlertCircle,
  Info,
  Filter,
  SlidersHorizontal,
  ArrowRight,
  ArrowLeft,
} from 'lucide-react'

export const ICONS = {
  secure: ShieldCheck,
  returns: RotateCcw,
  reviews: MessageSquareText,
  verified: BadgeCheck,
  delivery: Truck,
  fastDelivery: Zap,
  cod: Banknote,
  upi: Smartphone,
  warranty: ShieldPlus,
  trust: ShieldHalf,
  match: Target,
  compare: Columns3,
  wishlist: Heart,
  cart: ShoppingCart,
  seniorMode: Accessibility,
  support: Headset,
  offers: BadgePercent,
  priceDrop: TrendingDown,
  location: MapPin,
  categories: LayoutGrid,
  laptop: Laptop,
  headphones: Headphones,
  smartphone: Smartphone,
  camera: Camera,
  watch: Watch,
  tablet: Tablet,
  speaker: Speaker,
  tv: Tv,
  search: Search,
  user: User,
  menu: Menu,
  x: X,
  star: Star,
  minus: Minus,
  plus: Plus,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash2,
  edit: Edit,
  check: CheckCircle,
  alert: AlertCircle,
  info: Info,
  filter: Filter,
  sliders: SlidersHorizontal,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
}

export const getIcon = (name) => {
  const key = name?.toLowerCase?.() || ''
  return ICONS[key] || null
}
