export const ROUTES = {
  HOME: '/',
  SEARCH: '/search',
  PRODUCT_DETAIL: '/product/:id',
  LOGIN: '/login',
  REGISTER: '/register',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDERS: '/orders',
  ORDER_TRACKING: '/orders/:id',
  PROFILE: '/profile',
  SELLER_DASHBOARD: '/seller',
  SELLER_PRODUCTS: '/seller/products',
  SELLER_ADD_PRODUCT: '/seller/products/add',
  SELLER_EDIT_PRODUCT: '/seller/products/edit/:id',
  SELLER_INVENTORY: '/seller/inventory',
  SELLER_ORDERS: '/seller/orders',
  ADMIN_DASHBOARD: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_REVIEWS: '/admin/reviews',
  DESIGN_PROCESS: '/design-process',
  CASE_STUDY: '/case-study',
  COMPARE: '/compare',
}
